-- 코드를 입력하세요
SELECT P.PRODUCT_ID , P.PRODUCT_NAME ,SUM(P.PRICE*O.AMOUNT) AS TOTAL_PRICE
from FOOD_PRODUCT P INNER JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE PRODUCE_DATE LIKE "2022-05%"
GROUP BY 1
ORDER BY 3 DESC , 1 ASC