SELECT  CATEGORY,M_P,PRODUCT_NAME
FROM
(
SELECT CATEGORY,MAX(PRICE) AS M_P,PRODUCT_NAME, RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC ) AS RK
from FOOD_PRODUCT
where CATEGORY in('과자', '국', '김치', '식용유')
group by 1,3
) A 
WHERE RK = 1
ORDER BY 2 DESC